apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-linkerd
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure-jaeger
    - name: infrastructure-prometheus
    - name: infrastructure-openfaas
    - name: infrastructure-mysql
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/infrastructure/linkerd
  postBuild:
    substitute:
      cert_expiry: "2022-10-15T16:30:39Z"  
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: linkerd
      namespace: linkerd